staticDir = ['static']
enableEmoji = true

baseurl = "/"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
pagination.pagerSize = 5

title = "BLOG.GOOSE.LOVE"
subtitle = "A blog I made"
# leave empty to disable, enter display text to enable
# lastModDisplay = ""

enableGitInfo = true

[params]
  keywords = "tech, math, games, indie, geek"
  copyright = ""
  menuMore = "Show more"
  writtenBy = "Written by"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  minuteReadingTime = "min read"
  dateFormatSingle = "2006-01-02"
  dateFormatList = "2006-01-02"
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true


[logo]
    logoText = "blog.goose.love"
    logoHomeLink = "/"
  # or
  #
  # path = "/img/your-example-logo.svg"
  # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://goose.love/"
  [[menu.main]]
    identifier = "sponsor"
    name = "Support my work ‚ù§"
    url = "https://github.com/sponsors/blyxyas"

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1
